export const GPS_MAX_ANTIGUEDAD_MINUTOS = 2;
export const GPS_RADIO_DETECCION_PARADA_METROS = 80;
export const GPS_VELOCIDAD_MINIMA_MOVIMIENTO_KMH = 3;
export const GPS_RADIO_FUERA_RUTA_METROS = 150;

export const VIGITRACK_SYNC_INTERVAL_NORMAL_SECONDS = 30;
export const VIGITRACK_SYNC_INTERVAL_NEAR_STOP_SECONDS = 15;
export const GPS_RADIO_CERCANIA_PARADA_METROS = 150;

export const GPS_OPERATION_START_HOUR = 5;
export const GPS_OPERATION_START_MINUTE = 30;

export const GPS_OPERATION_END_HOUR = 20;
export const GPS_OPERATION_END_MINUTE = 30;